name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Go Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          args: --timeout=5m

      - name: Go Mod Download
        run: go mod download

      - name: Go Test
        run: go test -race ./...

      - name: Go Build amd64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o kubectl-parallel-exec-amd64

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
